<?php
///////////////////////////////////////////////////////////
// File: dbinfo.inc
// Purpose: Set variables used to manage and access 
//          a membership database
// Usage: 
//          Place this file in the parent directory,
//          which should restrict direct access to this 
//          file by web clients
// Revision History:
// Date      Pgmr Descr
//  4/ 4/02  ddw  Created
//  8 29/15  ddw  Replaced data from original app with
//                placeholders
///////////////////////////////////////////////////////////
$DbInfoInc = true;

$host='localhost';
$user='USERNAME';
$passwd='PASSWORD';
$dbname='DBNAME';

